---
jobs:
- name: job
  public: true
  plan:
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: public.ecr.aws/b4v4v1s0/python }
      run:
        path: python
        args: ["json_checker.py"]